version: '3.8'

services:
  database:
    build:
      context: ./docker/database
    environment:
      - MYSQL_DATABASE=development
      - MYSQL_USER=development
      - MYSQL_PASSWORD=development
      - MYSQL_ROOT_PASSWORD=development
    ports:
      - "3306:3306"